export  const button={
    LEFT_TOP_BUTTON_CLICKED:"LEFT_TOP_BUTTON_CLICKED",
    LEFT_DOWN_BUTTON_CLICKED:"LEFT_DOWN_BUTTON_CLICKED",
    RIGHT_TOP_BUTTON_CLICKED:"RIGHT_TOP_BUTTON_CLICKED",
    RIGHT_DOWN_BUTTON_CLICKED:"RIGHT_DOWN_BUTTON_CLICKED",
    RESET:"RESET",
}